[package]
name = "turing-machine"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
iced = { version = "0.6.0", features = ["debug"] }
num-traits = "0.2"
const-str = "0.5.3"
rfd = "0.10.0"